improve integration output, write errors to stderr

diff --git a/init/common b/init/common
--- a/init/common
+++ b/init/common
@@ -13,7 +13,6 @@ res=$?
 if [ $res = 0 ]; then
     module load $mod
     $@
-    exit $?
 elif [ $res = 2 ]; then
-    echo "$1: command not found!"
+    echo "$1: command not found!" 1>&2
 fi
